import { Collection, Db, ObjectId, MongoClient } from "mongodb";
import Mongo_client_Component from "./mongodb";
import { Group, GroupMember, SubjectInfo, Task } from "@/types";

/**
 * Groups & tasks persistence (MongoDB collections: `groups`, `tasks`).
 * Follows the app's existing convention: collection `data` holds one doc per
 * student (username) with their profile (`user`) and cached schedule/exam.
 */

export const HCMUT_EMAIL_RE = /^[a-z0-9._%+-]+@hcmut\.edu\.vn$/i;

/** Stored shape: _id is generated by Mongo, `id` is derived on read. */
type GroupDoc = Omit<Group, "id"> & { _id?: ObjectId };
type TaskDoc = Omit<Task, "id"> & { _id?: ObjectId };

interface Collections {
    client: MongoClient;
    db: Db;
    groups: Collection<GroupDoc>;
    tasks: Collection<TaskDoc>;
    data: Collection;
}

async function collections(): Promise<Collections> {
    const client = await Mongo_client_Component();
    await client.connect();
    const db = client.db("hcmut");
    return {
        client,
        db,
        groups: db.collection("groups"),
        tasks: db.collection("tasks"),
        data: db.collection("data"),
    };
}

function toGroup(doc: any): Group {
    return {
        id: doc._id.toString(),
        name: doc.name,
        courseCode: doc.courseCode ?? "",
        courseName: doc.courseName ?? "",
        createdBy: doc.createdBy,
        members: doc.members ?? [],
        createdAt: doc.createdAt,
    };
}

function toTask(doc: any): Task {
    return {
        id: doc._id.toString(),
        groupId: doc.groupId,
        title: doc.title,
        description: doc.description ?? "",
        assigneeEmail: doc.assigneeEmail ?? undefined,
        status: doc.status ?? "todo",
        deadline: doc.deadline ?? undefined,
        createdBy: doc.createdBy,
        createdAt: doc.createdAt,
    };
}

/** Cached profile of an app user (the `user` field of their `data` doc). */
export async function getUserProfile(username: string): Promise<{
    fullName: string;
    email: string;
    mssv: string;
} | null> {
    const { data } = await collections();
    const doc = await data.findOne(
        { username },
        { projection: { _id: 0, user: 1 } }
    );
    if (!doc?.user) return null;
    return {
        fullName: doc.user.name ?? username,
        email: doc.user.email ?? "",
        mssv: doc.user.MSSV ?? doc.user.id ?? "",
    };
}

export async function getGroup(groupId: string): Promise<Group | null> {
    const { groups } = await collections();
    let doc: any = null;
    try {
        doc = await groups.findOne({ _id: toObjectId(groupId) });
    } catch {
        return null;
    }
    return doc ? toGroup(doc) : null;
}

export async function listGroupsForUser(identity: string): Promise<Group[]> {
    const { groups } = await collections();
    const id = identity.trim();
    const docs = await groups
        .find({
            $or: [
                { "members.studentId": id },
                { createdBy: id },
                { "members.username": id },
            ],
        })
        .sort({ createdAt: -1 })
        .toArray();
    return docs.map(toGroup);
}

/** Identity-agnostic leader check: leader member's MSSV or legacy `createdBy`/username. */
export function isLeaderOf(group: Group, identity: string): boolean {
    const id = identity.trim();
    if (!id) return false;
    return (
        group.createdBy === id ||
        group.members.some((m) => m.isLeader && matchesMemberIdentity(m, id))
    );
}

/** Identity-agnostic member check: MSSV first, then username/email prefix. */
export function isMemberOf(group: Group, identity: string): boolean {
    const id = identity.trim();
    if (!id) return false;
    return (
        group.createdBy === id ||
        group.members.some((m) => matchesMemberIdentity(m, id))
    );
}

function matchesMemberIdentity(
    member: GroupMember,
    identity: string
): boolean {
    return (
        Boolean(member.studentId) && member.studentId === identity ||
        (member.username ?? "") === identity ||
        member.email.split("@")[0] === identity
    );
}

export async function createGroup(input: {
    name: string;
    courseCode: string;
    courseName: string;
    username: string;
    fullName: string;
    email: string;
    mssv: string;
}): Promise<Group> {
    const { groups } = await collections();
    const leader: GroupMember = {
        studentId: input.mssv,
        email: input.email,
        fullName: input.fullName,
        isLeader: true,
        joinedAt: new Date().toISOString(),
        scheduleShared: true,
        username: input.username,
    };
    const doc = {
        name: input.name.trim(),
        courseCode: input.courseCode.trim(),
        courseName: input.courseName.trim(),
        createdBy: input.username,
        members: [leader],
        createdAt: new Date().toISOString(),
    };
    const { insertedId } = await groups.insertOne(doc);
    return toGroup({ _id: insertedId, ...doc });
}

export async function updateGroup(
    groupId: string,
    patch: { name?: string; courseCode?: string; courseName?: string }
): Promise<Group | null> {
    const { groups } = await collections();
    const $set: Record<string, string> = {};
    if (patch.name !== undefined) $set.name = patch.name.trim();
    if (patch.courseCode !== undefined) $set.courseCode = patch.courseCode.trim();
    if (patch.courseName !== undefined) $set.courseName = patch.courseName.trim();
    await groups.updateOne({ _id: toObjectId(groupId) }, { $set });
    return getGroup(groupId);
}

export async function deleteGroup(groupId: string): Promise<void> {
    const { groups, tasks } = await collections();
    await tasks.deleteMany({ groupId });
    await groups.deleteOne({ _id: toObjectId(groupId) });
}

/**
 * Resolve an HCMUT email to a known app user (for invites).
 * Matches against the cached profile (`user.email` = mybk orgEmail)
 * and falls back to the MSSV prefix convention.
 */
export async function resolveUserByEmail(
    email: string
): Promise<{ username: string; mssv: string; fullName: string } | null> {
    const normalized = email.toLowerCase();
    const mssv = normalized.split("@")[0];
    const { data } = await collections();
    const docs = await data
        .find({}, { projection: { _id: 0, username: 1, user: 1 } })
        .toArray();

    const match = docs.find(
        (doc: any) =>
            String(doc?.user?.email ?? "").toLowerCase() === normalized ||
            String(doc?.user?.MSSV ?? "").toLowerCase() === mssv
    );
    if (!match) return null;

    return {
        username: match.username,
        mssv: match.user?.MSSV ?? mssv,
        fullName: match.user?.name ?? mssv,
    };
}

/** Resolve an app username to its profile (for adding members from the DB). */
export async function resolveUserByUsername(username: string): Promise<{
    username: string;
    mssv: string;
    fullName: string;
    email: string;
} | null> {
    const { data } = await collections();
    const doc = await data.findOne(
        { username },
        { projection: { _id: 0, username: 1, user: 1 } }
    );
    if (!doc) return null;
    return {
        username: doc.username,
        mssv: doc.user?.MSSV ?? doc.user?.id ?? "",
        fullName: doc.user?.name ?? doc.username,
        email: doc.user?.email ?? `${doc.username}@hcmut.edu.vn`,
    };
}

/** Search the app user database (name / username / email / MSSV). */
export async function searchUsers(
    query: string,
    excludeEmails: string[],
    limit = 20
): Promise<{
    username: string;
    fullName: string;
    mssv: string;
    email: string;
}[]> {
    const term = query.trim().toLowerCase();
    const { data } = await collections();
    const docs = await data
        .find(
            {},
            { projection: { _id: 0, username: 1, user: 1 }, limit }
        )
        .toArray();
    const excluded = new Set(excludeEmails.map((e) => e.toLowerCase()));
    return docs
        .filter((doc: any) => {
            const email = String(doc?.user?.email ?? "").toLowerCase();
            const name = String(doc?.user?.name ?? "").toLowerCase();
            const mssv = String(doc?.user?.MSSV ?? "").toLowerCase();
            const username = String(doc?.username ?? "").toLowerCase();
            if (email && excluded.has(email)) return false;
            if (term.length === 0) return Boolean(email);
            return (
                name.includes(term) ||
                username.includes(term) ||
                mssv.includes(term) ||
                email.includes(term)
            );
        })
        .map((doc: any) => ({
            username: doc.username,
            fullName: doc.user?.name ?? doc.username,
            mssv: doc.user?.MSSV ?? doc.user?.id ?? "",
            email: doc.user?.email ?? `${doc.username}@hcmut.edu.vn`,
        }));
}

export async function addMember(
    group: Group,
    email: string,
    resolved: { username: string; mssv: string; fullName: string } | null
): Promise<Group> {    const { groups } = await collections();
    const member: GroupMember = {
        studentId: resolved?.mssv ?? email.split("@")[0],
        email,
        fullName: resolved?.fullName ?? email,
        isLeader: false,
        joinedAt: new Date().toISOString(),
        scheduleShared: Boolean(resolved),
        username: resolved?.username ?? undefined,
    };
    await groups.updateOne(
        { _id: toObjectId(group.id) },
        { $push: { members: member } }
    );
    return (await getGroup(group.id))!;
}

export async function removeMember(group: Group, email: string): Promise<Group> {
    const { groups } = await collections();
    await groups.updateOne(
        { _id: toObjectId(group.id) },
        { $pull: { members: { email } } }
    );
    return (await getGroup(group.id))!;
}

export async function listTasks(groupId: string): Promise<Task[]> {
    const { tasks } = await collections();
    const docs = await tasks
        .find({ groupId })
        .sort({ createdAt: 1 })
        .toArray();
    return docs.map(toTask);
}

export async function listTasksForUser(username: string): Promise<Task[]> {
    const groups = await listGroupsForUser(username);
    const groupIds = groups.map((g) => g.id);
    if (groupIds.length === 0) return [];
    const { tasks } = await collections();
    const docs = await tasks.find({ groupId: { $in: groupIds } }).toArray();
    return docs.map(toTask);
}

export async function createTask(input: {
    groupId: string;
    title: string;
    description: string;
    assigneeEmail?: string;
    deadline?: string;
    createdBy: string;
}): Promise<Task> {
    const { tasks } = await collections();
    const doc = {
        groupId: input.groupId,
        title: input.title.trim(),
        description: input.description.trim(),
        assigneeEmail: input.assigneeEmail,
        deadline: input.deadline,
        status: "todo" as const,
        createdBy: input.createdBy,
        createdAt: new Date().toISOString(),
    };
    const { insertedId } = await tasks.insertOne(doc);
    return toTask({ _id: insertedId, ...doc });
}

export async function updateTask(
    taskId: string,
    patch: {
        status?: "todo" | "in_progress" | "done";
        title?: string;
        description?: string;
        assigneeEmail?: string;
        deadline?: string;
    }
): Promise<Task | null> {
    const { tasks } = await collections();
    await tasks.updateOne({ _id: toObjectId(taskId) }, { $set: patch });
    const doc = await tasks.findOne({ _id: toObjectId(taskId) });
    return doc ? toTask(doc) : null;
}

export async function deleteTask(taskId: string): Promise<void> {
    const { tasks } = await collections();
    await tasks.deleteOne({ _id: toObjectId(taskId) });
}

/**
 * Load every member's cached schedule (from their `data` doc).
 * Members whose username is unknown to the app are skipped.
 */
export async function loadMemberSchedules(
    group: Group
): Promise<{ studentId: string; fullName: string; courses: SubjectInfo[] }[]> {
    const usernames = group.members
        .filter((m) => m.username)
        .map((m) => m.username!);

    const { data } = await collections();
    const docs = await data
        .find({ username: { $in: usernames } }, { projection: { _id: 0, username: 1, schedule: 1 } })
        .toArray();

    const byUsername = new Map(docs.map((d: any) => [d.username, d.schedule ?? []]));

    return group.members
        .filter((m) => m.username && byUsername.has(m.username!))
        .map((m) => ({
            studentId: m.studentId,
            fullName: m.fullName,
            courses: byUsername
                .get(m.username!)!.filter((item: unknown) => typeof item !== "string")
                .map((s: SubjectInfo) => s),
        }));
}

function toObjectId(id: string): ObjectId {
    return new ObjectId(id);
}
